const main = document.querySelector('main');
const A = 'assets/';
const arrow = '<i data-lucide="arrow-up-right"></i>';
const play = '<i data-lucide="play"></i>';
const catalog=window.PORTFOLIO;
const mediaIndex=Object.fromEntries([...catalog.series.flatMap(s=>s.items),...catalog.animations].map(v=>[v.id,v]));
const posters = [
 ['restaurant-cover','烧鸟贤人 · 线下 KT 板'],['delivery','鳥贤 · 冬日配送'],['beer','鳥贤 · 一番榨畅饮'],['summer','钟韩 · 盛夏冰爽'],['moon','钟韩 · 中秋节庆'],['national','钟韩 · 国庆节庆'],['community','钟韩 · 社群迎新'],['opening','鳥贤 · 开业酬宾'],['qixi','钟韩 · 七夕套餐']
];
const img=(name,alt,cls='',eager=false)=>`<img class="${cls}" src="${A}${name}" alt="${alt}" loading="${eager?'eager':'lazy'}" decoding="async">`;
const photo=(name,title)=>`<button class="image-button" data-image="${name}" data-title="${title}" aria-label="放大：${title}">${img(name,title)}<span class="zoom-icon"><i data-lucide="expand"></i></span></button>`;
const sectionHead=(n,en,title,desc='')=>`<div class="section-heading"><div><p class="eyebrow">${n} / ${en}</p><h2>${title}</h2></div>${desc?`<p class="section-description">${desc}</p>`:''}</div>`;
function videoTile(v,label=''){return `<button class="video-tile" data-video="${v.id}" data-title="${v.title}"><div class="video-tile-image">${img(v.poster,v.title)}<span class="play-disc">${play}</span><span class="duration">${v.duration}</span>${v.id==='bedtime-009'?'<span class="featured-badge">首推作品</span>':''}</div><div class="video-tile-copy"><span>${label}</span><h3>${v.title}</h3><i data-lucide="arrow-up-right"></i></div></button>`;}
function seriesCollection(selected='bedtime'){const s=catalog.series.find(s=>s.id===selected)||catalog.series[0];return `<div class="series-collection"><div class="collection-tabs" role="tablist" aria-label="视频系列">${catalog.series.map(x=>`<button role="tab" id="tab-${x.id}" aria-selected="${x.id===s.id}" aria-controls="series-panel" tabindex="${x.id===s.id?0:-1}" data-series="${x.id}">${x.name}</button>`).join('')}</div><div id="series-panel" role="tabpanel" aria-labelledby="tab-${s.id}"><div class="series-summary"><span>${s.description}</span><span>系列代表作</span></div><div class="series-videos representative-layout">${videoTile(s.items[0],s.name)}<div class="series-context"><section class="account-feature"><p class="eyebrow">MY CONTENT CHANNEL / 抖音</p><h3>纸上有月光</h3><p class="account-tagline">每天翻一页好故事。</p><p>睡前小故事、经典童话、好书推荐，讲给小朋友，也讲给还愿意慢慢听故事的大人。</p><p class="account-ownership">我实际运营的内容账号 · AI 工作流制作，人工审核发布</p><div class="account-actions"><a class="dark-button" href="https://v.douyin.com/Bb-jFQexJOc/" target="_blank" rel="noopener noreferrer">去抖音看更多 <i data-lucide="external-link"></i></a><div class="account-number"><span>抖音号：97490601572</span><button type="button" data-copy-douyin aria-label="复制抖音号" title="复制抖音号"><i data-lucide="copy"></i></button></div></div><p class="copy-status" role="status" aria-live="polite"></p></section><div class="production-note"><p class="eyebrow">BEHIND THE WORK</p><h3>从选题，到成片。</h3><p>文案、图像、配音、字幕与剪辑，通过多 Agent 分工串联。</p><a href="#/project/video" class="text-link">查看项目方法 ${arrow}</a></div></div></div></div></div>`;}
function productCards(){return `<div class="product-directory">${catalog.products.map((p,i)=>`<a href="#/project/commerce/${p.id}" class="product-entry"><div class="product-entry-image">${img(p.images[0].file,p.name)}<span>${String(i+1).padStart(2,'0')}</span></div><h3>${p.name}</h3><p>${p.images.length} 张作品 ${arrow}</p></a>`).join('')}</div>`;}
function productGallery(id='wipes'){const p=catalog.products.find(p=>p.id===id)||catalog.products[0];return `<div class="product-case"><nav class="product-tabs" aria-label="商品项目">${catalog.products.map(x=>`<a href="#/project/commerce/${x.id}" ${x.id===p.id?'aria-current="page"':''}>${x.name}</a>`).join('')}</nav><div class="product-title"><div><p class="eyebrow">PRODUCT COLLECTION</p><h2>${p.name}</h2><p>${p.summary}</p></div><span>${p.images.length} 张作品</span></div><div class="finished-gallery">${p.images.map((im,i)=>`<figure>${photo(im.file,`${p.name} · ${im.title}`)}<figcaption><span>${im.title}</span><span>${String(i+1).padStart(2,'0')}</span></figcaption></figure>`).join('')}</div></div>`;}
function home(){return `
 <section class="hero">
  ${img('hero.jpg','个人 AI 短片《信》中的室内场景','hero-image',true)}<div class="hero-shade"></div>
  <div class="hero-top"><span>独立实践 / 持续创作</span><span>GUANGZHOU, CHINA</span></div>
  <div class="hero-content"><p class="hero-role">多 Agent 工作流实践者 · AI 内容创作者</p><h1>Wilson<span>.</span></h1><div class="hero-bottom"><p>AI 工作流搭建<br>视频生产与商业视觉</p><a class="light-button" href="#/projects">浏览精选作品 <i data-lucide="arrow-down-right"></i></a></div></div>
  <div class="hero-index"><a href="#/project/video"><span>01</span> 多系列视频 ${arrow}</a><a href="#/project/commerce"><span>02</span> 电商视觉 ${arrow}</a><a href="#/project/restaurant"><span>03</span> 餐饮内容 ${arrow}</a></div>
  <button class="hero-credit" data-video="film" data-title="《信》 · 个人 AI 短片">${play}<span>画面选自个人短片《信》</span></button>
 </section>
 <div class="intro-strip"><p>从餐饮现场，到 AI 实践。</p><span>蓝带厨艺背景 · 主厨与门店经营经历</span><a href="#/contact">广州 / 远程 · 求职与项目合作 ${arrow}</a></div>
 <section class="profile-brief"><div><span class="eyebrow">WHAT I DO</span><p>拆解需求、搭建流程，<br>把内容制作到可交付。</p></div><div><span class="eyebrow">MY CONTRIBUTION</span><p>策划与文案 / 工具集成<br>视觉方向 / 修改与验收</p></div><div><span class="eyebrow">IN THIS PORTFOLIO</span><p><strong>5</strong> 款商品 <strong>5</strong> 个内容系列<br><strong>5</strong> 集动画 <strong>9</strong> 张餐饮海报</p></div></section>
 <section class="section" id="projects">
  ${sectionHead('01','CONTENT SYSTEMS','多系列视频作品集','从《皇帝的新装》开始，看看同一套生产方法如何服务不同内容。')}
  <div id="home-series">${seriesCollection()}</div>
 </section>
 <section class="section commerce-section">
  ${sectionHead('02','COMMERCIAL VISUALS','一件商品，多面呈现。','五款母婴产品，按商品浏览完整主图、细节展示与场景作品。')}
  ${productCards()}
  <div class="collection-foot"><p>我的职责：需求整理、视觉方向、工作流搭建与成图审核</p><a href="#/project/commerce">全部电商作品 ${arrow}</a></div>
 </section>
 <section class="section restaurant-section">
  ${sectionHead('03','RESTAURANT PRACTICE','懂门店，也做内容。','从自己的经营现场出发，独立完成活动方案、文案与宣传物料。')}
  <a class="restaurant-project" href="#/project/restaurant"><div class="restaurant-preview">${img('restaurant-cover.webp','烧鸟贤人 KT 板')}${img('beer.webp','一番榨畅饮海报')}${img('delivery.webp','冬日配送海报')}</div><div class="restaurant-project-copy"><p class="eyebrow">REAL BUSINESS / 餐饮内容</p><h3>在真实生意里，<br>把创意落地。</h3><p>从活动方案、文案到最终海报，<br>独立完成，实际用于门店宣传。</p><span class="text-link">查看餐饮案例 ${arrow}</span><span class="project-number">03</span></div></a>
 </section>
 <section class="films-section section" id="films">${sectionHead('04','MOTION & STORIES','影像叙事与系列创作','个人 AI 短片《信》，以及《健身动物园》前五集。')}
  <div class="feature-film-row"><button class="film-feature" data-video="film" data-title="《信》 · AI 原创剧情短片">${img('film.jpg','《信》短片画面')}<span class="play-disc">${play}</span><div class="film-caption"><div><p>AI SHORT FILM / 原创剧情短片</p><h3>信</h3></div><span>观看完整影片 ${arrow}</span></div></button><div class="film-editorial"><p class="eyebrow">信 / 写给岁月的家书</p><h3>致敬远行的人，<br>也致敬等待的人。</h3><p>一封封迟到三十年的家书，替一个没能回家的父亲，终于回到了家人身边。</p><a href="#/project/film" class="text-link">故事与创作初衷 ${arrow}</a></div></div>
  <div class="advertising-entry"><a href="#/project/advertising" class="advertising-cover">${img('advertising.jpg','新年一起旺广告封面')}<span class="play-disc">${play}</span></a><div><p class="eyebrow">ADVERTISING / 广告工作流</p><h3>新年一起旺</h3><p>以旺仔牛奶为创作对象的职场轻喜剧。<br>从创意、剧本、分镜到成片的完整实践。</p><p class="ad-disclosure">个人参赛作品 · 非品牌委托</p><a class="text-link" href="#/project/advertising">观看成片与项目方法 ${arrow}</a></div></div><div class="animation-heading"><h3>健身动物园</h3><span>3D 动画系列 / 全 5 集</span></div><div class="animation-grid">${catalog.animations.map(v=>videoTile(v,`第 ${v.episode} 集`)).join('')}</div>
 </section>
 <section class="section app-section"><div class="app-copy"><p class="eyebrow">05 / PRODUCT EXPLORATION</p><h2>今天吃什么？<br>从自己的困扰出发。</h2><p>把厨师经验带进一个小工具。开饭助手根据家中现有食材匹配菜谱，整理缺材清单，并提供做菜步骤。</p><div class="inline-tags"><span>食材匹配</span><span>做菜 SOP</span><span>安卓本地原型</span></div><a class="dark-button" href="#/project/kaifan">体验开饭助手 ${arrow}</a></div><a class="app-preview" href="#/project/kaifan" aria-label="查看开饭助手案例">${img('kaifan.webp','开饭助手实际界面截图')}<span class="app-preview-label">开饭助手 / 本地应用原型</span></a></section>
 <section class="about-section section" id="about"><p class="eyebrow">06 / ABOUT WILSON</p><div class="about-layout"><h2>做过主厨，<br>经营过餐厅。<br><span>现在，也搭建工作流。</span></h2><div class="about-copy"><p>我毕业于澳洲蓝带厨师学院，回国后从事过酒店、日式简餐、韩式料理及烧烤，也参与经营过韩式餐厅与日式烧鸟店。</p><p>从菜单、活动到宣传物料，我习惯围绕实际需求把事情做完整。最初使用 AI 辅助门店内容与管理工作，后来开始系统学习 AI 应用，逐步搭建自己的多 Agent 工作流。</p><p>目前，我将这些方法应用于视频生产、电商视觉与应用原型开发，持续通过实际项目调整和验证。</p><div class="about-facts"><div><span>背景</span><strong>蓝带厨艺 · 餐饮经营</strong></div><div><span>当前实践</span><strong>AI 工作流 · 内容创作</strong></div><div><span>合作地点</span><strong>广州 / 远程</strong></div></div></div></div></section>
 <section class="contact-section section" id="contact"><div><p class="eyebrow">LET’S WORK TOGETHER</p><h2>聊聊下一件<br>值得做的事<span>。</span></h2></div><div class="contact-copy"><p>全职机会 / 项目合作</p><p>AI 应用与工作流搭建、内容自动化、<br>餐饮活动内容及电商视觉制作。</p><div class="contact-pending"><i data-lucide="message-circle"></i><div><strong>微信联系</strong><span class="wechat-id">q444542632</span></div><button class="copy-wechat" data-copy-wechat aria-label="复制微信号" title="复制微信号"><i data-lucide="copy"></i></button></div><p class="wechat-status" role="status" aria-live="polite"></p><small>广州 · 可沟通远程合作</small></div></section>`;}
const cases={
 film:{title:'信 · 写给岁月的家书'},
 advertising:{n:'06',en:'ADVERTISING WORKFLOW',title:'新年一起旺',lead:'以旺仔牛奶为创作对象的职场轻喜剧广告：把一句冷嘲，变成送给同事的新年祝福。',role:'创意策划、剧本与分镜、AI 生成与成片制作',state:'个人参赛作品 · 非品牌委托',tools:'广告 Agent 工作流 / 即梦 / 后期剪辑',steps:['品牌与创意方向','剧本与导演方案','人物产品与故事板','分段视频生成','剪辑与声音设计'],body:'围绕童年广告记忆与新年开工场景组织故事。项目中保留了剧本、导演视觉方案、资产清单、故事板质检、视频生成记录及后期声音方案，将创意到成片的各阶段串联起来。',boundary:'个人参赛创作，非旺仔品牌委托或官方广告，不代表品牌背书。此处播放原始成片，未进行画质增强；部分镜头的清晰度与连续性仍有提升空间。'},
 video:{n:'01',en:'CONTENT AUTOMATION',title:'把内容生产，\n串成工作流。',lead:'为自己运营的母婴内容账号搭建自动化生产流程，覆盖儿童科普、睡前故事、育儿知识与读物推荐。',role:'工作流搭建与迭代、内容方向、成品审核',state:'个人账号实际使用 · 人工审核发布',tools:'Codex / ComfyUI / IndexTTS / Remotion',steps:['选题与资料','脚本与视觉规划','图像与配音生成','字幕与视频合成','人工审核与发布'],body:'不同系列共用生产工具，但保留各自的文案、字幕与视觉规则。通过角色分工、明确输入输出和本地记录，把反复执行的生产步骤组织起来。',boundary:'自动化覆盖内容生产环节，最终效果与发布由我确认。当前展示的是本地运行实践，未宣称无人值守或已完成客户环境部署。'},
 commerce:{n:'02',en:'ECOMMERCE VISUALS',title:'从一件商品，\n到一套视觉。',lead:'将商品照片与产品资料，组织成主图、辅助图、详情页、海报及按需制作的视频物料。',role:'需求整理、工作流搭建、视觉方向与人工验收',state:'个人电商实践 · 展示样例',tools:'Codex / RunningHub / ComfyUI / 即梦',steps:['产品资料','卖点与平台分析','设计与资产准备','分模块生成','修正与交付'],body:'以宝宝洗澡盆为例，围绕容量、座凳、结构与使用场景安排图片分工。详情页分模块生成后拼接，出现问题时针对单个模块修正，并保留不同版本。',boundary:'图片用于展示生产能力，不作为销量或转化率证明。商业使用前仍需核对产品结构、文案与具体参数。'},
 restaurant:{n:'03',en:'RESTAURANT CONTENT',title:'在真实生意里，\n把创意落地。',lead:'从活动方案到宣传物料，围绕真实门店的产品、节日、社群与配送需求，独立完成策划和制作。',role:'活动策划、文案、视觉方向与最终制作',state:'已实际使用 · 自有经营项目',tools:'DeepSeek / 即梦 / 实拍素材 / Photoshop',steps:['明确活动需求','方案与文案','视觉构思','生成素材与实拍','排版修字与应用'],body:'使用 DeepSeek 辅助活动策划与视觉构思，通过即梦生成素材，结合实拍照片，再在 Photoshop 中进行基础抠图、排版和文字修正。活动方案及最终呈现由我独立负责。',boundary:'以下为本人参与经营项目中的历史宣传物料，已获准公开。海报中的价格、时间与优惠仅记录当时活动，不代表当前经营信息；不将其描述为外部客户委托。'},
 kaifan:{n:'04',en:'PRODUCT EXPLORATION',title:'打开冰箱之后，\n不再为选菜发愁。',lead:'开饭助手源于我自己的选择困难：根据家里已有的食材，找到更容易做的一餐。',role:'需求定义、产品功能规划、AI 辅助开发与体验迭代',state:'安卓本地应用原型 · 原版 H5 体验',tools:'AI 辅助开发 / JavaScript / Capacitor',steps:['登记已有食材','匹配本地菜谱','对比缺少材料','加入制作清单','按 SOP 做菜'],body:'从食材库存出发，匹配本地菜谱并排序，结合收藏、采购清单和分步骤做法形成日常做饭流程。把餐饮经验转化为功能设计，是这个项目的出发点。',boundary:'此处接入原项目 H5 前端副本，保留库存、饮食档案、忌口、收藏、制作清单与烹饪等现有交互。体验记录仅保存在当前浏览器，与原项目使用记录隔离。不包含后台及安卓原生能力；采购与会员入口仍为原型，不支持真实下单或付费。'}
};
function casePage(id,product){
 if(id==='film')return filmPage();
 const c=cases[id];let media='';
 if(id==='restaurant')media=`<div class="poster-gallery">${posters.map(([n,t])=>`<figure>${photo(n+'.webp',t)}<figcaption>${t}</figcaption></figure>`).join('')}</div>`;
 if(id==='commerce')media=productGallery(product);
 if(id==='video')media=seriesCollection();
 if(id==='kaifan')media=window.renderKitchenDemo();
 if(id==='advertising')media=`<div class="advertising-showcase">${videoTile({id:'advertising',poster:'advertising.jpg',title:'新年一起旺',duration:'01:06'},'职场轻喜剧广告 / 个人参赛作品')}<div><p class="eyebrow">FROM IDEA TO FILM</p><h2>把「汪」的误会，<br>变成「旺」的祝福。</h2><p>新年开工，妈妈寄来的一箱旺仔，成为办公室里一场误会的起点。产品随着情节出现，最终落到分享与祝福。</p><p>一部完整竖屏短片，也是一套广告工作流的实际成果。</p></div></div>`;
 return `<section class="case-heading section"><a class="back-link" href="#/projects"><i data-lucide="arrow-left"></i> 所有项目</a><p class="eyebrow">${c.n} / ${c.en}</p><h1>${c.title.replace('\n','<br>')}</h1><p class="case-lead">${c.lead}</p><div class="case-meta"><div><span>我的职责</span><p>${c.role}</p></div><div><span>项目状态</span><p>${c.state}</p></div><div><span>主要工具</span><p>${c.tools}</p></div></div></section><section class="case-body section">${media}<details class="method-details"><summary>项目方法与工作流 <i data-lucide="plus"></i></summary><p class="case-prose">${c.body}</p><ol class="process">${c.steps.map((s,i)=>`<li><span>0${i+1}</span><strong>${s}</strong></li>`).join('')}</ol></details><aside class="case-boundary"><span>项目说明</span><p>${c.boundary}</p></aside><div class="case-end"><a href="#/projects">返回精选项目 <i data-lucide="arrow-left"></i></a><a href="#/contact">聊聊合作 ${arrow}</a></div></section>`;
}
function icons(){window.lucide?.createIcons({attrs:{'stroke-width':1.6,'aria-hidden':'true'}});}
function render(){const route=location.hash.slice(2);const match=route.match(/^project\/(video|commerce|restaurant|kaifan|advertising|film)(?:\/([a-z]+))?$/);main.innerHTML=match?casePage(match[1],match[2]):home();document.title=match?`${match[1]==='commerce'?(catalog.products.find(p=>p.id===match[2])?.name||'电商视觉作品集'):cases[match[1]].title.replace('\n','')}｜Wilson`:'Wilson｜AI 工作流与影像作品集';icons();document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.hash===location.hash));requestAnimationFrame(()=>{if(!match&&['projects','films','about','contact'].includes(route))document.getElementById(route)?.scrollIntoView();else if(match?.[2])document.querySelector('.product-case')?.scrollIntoView({behavior:'instant'});else window.scrollTo(0,0);});}
function filmPage(){return `<article class="film-story"><section class="section film-story-head"><a class="back-link" href="#/films"><i data-lucide="arrow-left"></i> 返回影像作品</a><p class="eyebrow">WILSON / AI 原创剧情短片</p><h1>信<span>写给岁月的家书</span></h1><p class="film-logline">一封封迟到三十年的家书，<br>替一个没能回家的父亲，终于回到了家人身边。</p><div class="film-facts"><span>历史背景 · 虚构家庭</span><span>家书 / 分离 / 守候</span><span>片长 07:48</span></div><button class="film-feature film-story-player" data-video="film" data-title="《信》 / 《写给岁月的家书》">${img('film.jpg','AI 原创剧情短片《信》中的场景','',true)}<span class="play-disc">${play}</span><div class="film-caption"><span>观看完整影片</span><span>07:48 ${arrow}</span></div></button></section><section class="section film-story-body"><div class="film-story-row"><p class="eyebrow">01 / 故事</p><div><h2>有些思念，<br>只能写下，不能寄出。</h2><p>故事以中国核事业发展历史为背景，围绕一名投身秘密科研工作的丈夫、一位独自守家的妻子，以及在等待中长大的孩子展开。</p><p>因保密任务，丈夫长期无法回家，只能把对家人的思念写进一封封无法寄出的家书。多年后，尘封的信件终于送到妻儿手中，让迟到的爱与理解完成了一次归家。</p></div></div><div class="film-story-row"><p class="eyebrow">02 / 创作初衷</p><div><h2>一个人的远行，<br>是一个家庭共同的承担。</h2><p>我想借一个虚构家庭的故事，致敬那个年代为国家建设默默奉献的人。他们中的很多人长期隐姓埋名，不能说明去处，不能解释工作，也无法准时回到家人身边。</p><p>但我不希望故事只停留在“个人为国家牺牲”的宏大表达上。真正打动我的，是那些被留下的人：独自支撑家庭的妻子、在缺席中长大的孩子，以及把等待过成一生的家人。</p><blockquote>那些没有被写进历史名字里的人，<br>同样构成了时代的一部分。</blockquote><p>因此，《信》想表达的不只是奉献者的伟大，也包括等待者的坚韧。以家书为线索，致敬那些把青春献给远方的人，也致敬那些在远方等待的人。</p><p class="film-author">创作自述 / Wilson</p></div></div><aside class="case-boundary"><span>作品说明</span><p>本片为历史背景下的 AI 原创剧情短片，人物与家庭故事为虚构，并非纪录片或特定人物传记。“三十年”指片中故事的时间跨度。</p></aside><div class="case-end"><a href="#/films">返回影像作品 <i data-lucide="arrow-left"></i></a><a href="#/contact">聊聊合作 ${arrow}</a></div></section></article>`;}
const dialog=document.querySelector('#viewer');let previousFocus;let imageGroup=[],imagePosition=0;
function updateImage(){const target=imageGroup[imagePosition];document.querySelector('#viewer-content img').src=A+target.dataset.image;document.querySelector('#viewer-content img').alt=target.dataset.title;document.querySelector('#viewer-caption').textContent=`${target.dataset.title} · ${imagePosition+1} / ${imageGroup.length}`;}
function closeViewer(){dialog.close();document.querySelector('#viewer-content').replaceChildren();document.body.classList.remove('modal-open');previousFocus?.focus();}
document.addEventListener('click',e=>{const tab=e.target.closest('[data-series]');if(tab){const collection=tab.closest('.series-collection');const id=tab.dataset.series;collection.outerHTML=seriesCollection(id);icons();document.getElementById('tab-'+id)?.focus({preventScroll:true});return;}const target=e.target.closest('[data-image],[data-video]');if(!target)return;previousFocus=target;const content=document.querySelector('#viewer-content');content.replaceChildren();const el=document.createElement(target.dataset.video?'video':'img');el.src=A+(target.dataset.video?target.dataset.video+'.mp4?v=20260922-science-approved':target.dataset.image);if(target.dataset.video){el.controls=true;el.playsInline=true;el.autoplay=true;el.poster=A+(mediaIndex[target.dataset.video]?.poster||target.dataset.video+'.jpg');}else el.alt=target.dataset.title;content.append(el);document.querySelector('#viewer-caption').textContent=target.dataset.title;dialog.showModal();document.body.classList.add('modal-open');});
document.addEventListener('keydown',e=>{if(!e.target.matches('[data-series]')||!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const tabs=[...e.target.closest('[role=tablist]').querySelectorAll('[role=tab]')];const i=tabs.indexOf(e.target);tabs[e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length].click();});
document.addEventListener('click',e=>{const target=e.target.closest('[data-image],[data-video]');if(!target)return;document.querySelector('#previous-work').hidden=!target.dataset.image;document.querySelector('#next-work').hidden=!target.dataset.image;if(target.dataset.image){imageGroup=[...target.closest('.finished-gallery,.poster-gallery,.commerce-gallery')?.querySelectorAll('[data-image]')||[target]];imagePosition=imageGroup.indexOf(target);updateImage();}});
function shiftImage(direction){if(!imageGroup.length||!document.querySelector('#viewer-content img'))return;imagePosition=(imagePosition+direction+imageGroup.length)%imageGroup.length;updateImage();}
document.querySelector('#previous-work').addEventListener('click',()=>shiftImage(-1));document.querySelector('#next-work').addEventListener('click',()=>shiftImage(1));document.addEventListener('keydown',e=>{if(dialog.open&&['ArrowLeft','ArrowRight'].includes(e.key)&&document.querySelector('#viewer-content img')){e.preventDefault();shiftImage(e.key==='ArrowLeft'?-1:1);}});
document.querySelector('.close-viewer').addEventListener('click',closeViewer);dialog.addEventListener('cancel',e=>{e.preventDefault();closeViewer();});dialog.addEventListener('click',e=>{if(e.target===dialog)closeViewer();});
window.addEventListener('hashchange',()=>{if(dialog.open)closeViewer();render();});render();
document.addEventListener('click',async e=>{const button=e.target.closest('[data-copy-douyin]');if(!button)return;const status=button.closest('.account-feature').querySelector('.copy-status');try{await navigator.clipboard.writeText('97490601572');status.textContent='抖音号已复制';}catch{status.textContent='未能自动复制，请选中抖音号手动复制。';}});
document.addEventListener('click',async e=>{const button=e.target.closest('[data-copy-wechat]');if(!button)return;const status=button.closest('.contact-copy').querySelector('.wechat-status');try{await navigator.clipboard.writeText('q444542632');status.textContent='微信号已复制';}catch{status.textContent='未能自动复制，请选中微信号手动复制。';}});
